export const mockBlackList = [
  {
    index: 1,
    name: '강승우',
    studentId: '123456',
    phoneNumber: '010-1234-5678',
    minus: '10',
    reason: 'Misbehavior',
    registrationDate: '2024-01-01',
    isChecked: false,
    setReason: () => {},
    setIsChecked: () => {},
    isEdit: false,
  },
  {
    index: 2,
    name: '이보현',
    studentId: '654321',
    phoneNumber: '010-8765-4321',
    minus: '15',
    reason: 'Late to class',
    registrationDate: '2024-01-02',
    isChecked: false,
    setReason: () => {},
    setIsChecked: () => {},
    isEdit: false,
  },

  {
    index: 3,
    name: '이보현',
    studentId: '654321',
    phoneNumber: '010-8765-4321',
    minus: '15',
    reason: 'Late to class',
    registrationDate: '2024-01-02',
    isChecked: false,
    setReason: () => {},
    setIsChecked: () => {},
    isEdit: false,
  },
];
