import { PointMemberResponse, PointListResponse } from '@/types/point';

// Mock Data
export const mockPointMemberResponse: PointMemberResponse = {
  check: true,
  information: {
    pageInfo: {
      currentPage: 1,
      totalPage: 1,
      pageSize: 25,
      totalElements: 1,
    },
    dataList: [
      {
        id: 1,
        name: '이보현',
        studentNumber: '123456',
        phoneNumber: '010-1234-5678',
        bonusPoint: 10,
        minusPoint: 2,
        dormitory: 'Dorm A',
        room: 101,
      },
      {
        id: 2,
        name: '강승우',
        studentNumber: '654321',
        phoneNumber: '010-8765-4321',
        bonusPoint: 5,
        minusPoint: 1,
        dormitory: 'Dorm B',
        room: 202,
      },
      {
        id: 2,
        name: '강승우',
        studentNumber: '654321',
        phoneNumber: '010-8765-4321',
        bonusPoint: 5,
        minusPoint: 1,
        dormitory: 'Dorm B',
        room: 202,
      },
      {
        id: 2,
        name: '강승우',
        studentNumber: '654321',
        phoneNumber: '010-8765-4321',
        bonusPoint: 5,
        minusPoint: 1,
        dormitory: 'Dorm B',
        room: 202,
      },
      {
        id: 2,
        name: '강승우',
        studentNumber: '654321',
        phoneNumber: '010-8765-4321',
        bonusPoint: 5,
        minusPoint: 1,
        dormitory: 'Dorm B',
        room: 202,
      },
      {
        id: 2,
        name: '강승우',
        studentNumber: '654321',
        phoneNumber: '010-8765-4321',
        bonusPoint: 5,
        minusPoint: 1,
        dormitory: 'Dorm B',
        room: 202,
      },
      {
        id: 2,
        name: '강승우',
        studentNumber: '654321',
        phoneNumber: '010-8765-4321',
        bonusPoint: 5,
        minusPoint: 1,
        dormitory: 'Dorm B',
        room: 202,
      },
      {
        id: 2,
        name: '강승우',
        studentNumber: '654321',
        phoneNumber: '010-8765-4321',
        bonusPoint: 5,
        minusPoint: 1,
        dormitory: 'Dorm B',
        room: 202,
      },
      {
        id: 2,
        name: '강승우',
        studentNumber: '654321',
        phoneNumber: '010-8765-4321',
        bonusPoint: 5,
        minusPoint: 1,
        dormitory: 'Dorm B',
        room: 202,
      },
      {
        id: 2,
        name: '강승우',
        studentNumber: '654321',
        phoneNumber: '010-8765-4321',
        bonusPoint: 5,
        minusPoint: 1,
        dormitory: 'Dorm B',
        room: 202,
      },
      {
        id: 2,
        name: '강승우',
        studentNumber: '654321',
        phoneNumber: '010-8765-4321',
        bonusPoint: 5,
        minusPoint: 1,
        dormitory: 'Dorm B',
        room: 202,
      },
      {
        id: 2,
        name: '강승우',
        studentNumber: '654321',
        phoneNumber: '010-8765-4321',
        bonusPoint: 5,
        minusPoint: 1,
        dormitory: 'Dorm B',
        room: 202,
      },
      {
        id: 2,
        name: '강승우',
        studentNumber: '654321',
        phoneNumber: '010-8765-4321',
        bonusPoint: 5,
        minusPoint: 1,
        dormitory: 'Dorm B',
        room: 202,
      },
      {
        id: 2,
        name: '강승우',
        studentNumber: '654321',
        phoneNumber: '010-8765-4321',
        bonusPoint: 5,
        minusPoint: 1,
        dormitory: 'Dorm B',
        room: 202,
      },
      {
        id: 2,
        name: '강승우',
        studentNumber: '654321',
        phoneNumber: '010-8765-4321',
        bonusPoint: 5,
        minusPoint: 1,
        dormitory: 'Dorm B',
        room: 202,
      },
      {
        id: 2,
        name: '강승우',
        studentNumber: '654321',
        phoneNumber: '010-8765-4321',
        bonusPoint: 5,
        minusPoint: 1,
        dormitory: 'Dorm B',
        room: 202,
      },
      // Add more mock data as needed
    ],
  },
};

export const mockPointListResponse: PointListResponse = {
  check: true,
  information: [
    {
      pointId: 1,
      content: 'Good behavior',
      score: 5,
      pointType: 'BONUS',
    },
    {
      pointId: 2,
      content: 'Late to class',
      score: -3,
      pointType: 'MINUS',
    },
    // Add more mock data as needed
  ],
};
