import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import RecoilRootWrapper from '@/recoil/RecoilWrapper.tsx';
import Navigation from '@/components/organisms/Navigation/Navigation';
import Header from '@/components/organisms/Header/Header';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <head>
        {/* react-quill CSS 파일 링크 */}
        <link rel='stylesheet' href='https://unpkg.com/react-quill@1.3.3/dist/quill.snow.css' />
      </head>
      <body className='flex flex-col'>
        <div className='mb-30 fixed top-0 w-full'>
          <Header />
        </div>
        <div className='flex align-start ml-19 mt-132'>
          <nav className='mr-101 '>
            <Navigation />
          </nav>
          <div className='mt-7'>
            <RecoilRootWrapper>{children}</RecoilRootWrapper>
          </div>
        </div>
      </body>
    </html>
  );
}
