import type { Meta, StoryObj } from '@storybook/react';

import page from './page';

const meta: Meta<typeof page> = {
  title: 'app/resigns/page',
  component: page,
  tags: ['autodocs'],
  argTypes: {},
};

export default meta;

type Story = StoryObj<typeof page>;

const list = [
  {
    exitRequestmentId: 1,
    residentName: '김김김김',
    studentNumber: '99999999',
    dormitoryName: '명덕관(4인실)',
    roomSize: 0,
    roomNumber: 999,
    exitDate: '24.00.00',
    hasKey: true,
    createDate: '24.00.00',
    securityDepositReturnStatus: 'PAYMENT',
  },
  {
    exitRequestmentId: 1,
    residentName: '김김김김',
    studentNumber: '99999999',
    dormitoryName: '명덕관(4인실)',
    roomSize: 0,
    roomNumber: 999,
    exitDate: '24.00.00',
    hasKey: true,
    createDate: '24.00.00',
    securityDepositReturnStatus: 'PAYMENT',
  },
  {
    exitRequestmentId: 1,
    residentName: '김김김김',
    studentNumber: '99999999',
    dormitoryName: '명덕관(4인실)',
    roomSize: 0,
    roomNumber: 999,
    exitDate: '24.00.00',
    hasKey: true,
    createDate: '24.00.00',
    securityDepositReturnStatus: 'PAYMENT',
  },
  {
    exitRequestmentId: 1,
    residentName: '김김김김',
    studentNumber: '99999999',
    dormitoryName: '명덕관(4인실)',
    roomSize: 0,
    roomNumber: 999,
    exitDate: '24.00.00',
    hasKey: true,
    createDate: '24.00.00',
    securityDepositReturnStatus: 'PAYMENT',
  },
];

const listScroll = [
  {
    exitRequestmentId: 1,
    residentName: '김김김김',
    studentNumber: '99999999',
    dormitoryName: '명덕관(4인실)',
    roomSize: 0,
    roomNumber: 999,
    exitDate: '24.00.00',
    hasKey: true,
    createDate: '24.00.00',
    securityDepositReturnStatus: 'PAYMENT',
  },
  {
    exitRequestmentId: 1,
    residentName: '김김김김',
    studentNumber: '99999999',
    dormitoryName: '명덕관(4인실)',
    roomSize: 0,
    roomNumber: 999,
    exitDate: '24.00.00',
    hasKey: true,
    createDate: '24.00.00',
    securityDepositReturnStatus: 'PAYMENT',
  },
  {
    exitRequestmentId: 1,
    residentName: '김김김김',
    studentNumber: '99999999',
    dormitoryName: '명덕관(4인실)',
    roomSize: 0,
    roomNumber: 999,
    exitDate: '24.00.00',
    hasKey: true,
    createDate: '24.00.00',
    securityDepositReturnStatus: 'PAYMENT',
  },
  {
    exitRequestmentId: 1,
    residentName: '김김김김',
    studentNumber: '99999999',
    dormitoryName: '명덕관(4인실)',
    roomSize: 0,
    roomNumber: 999,
    exitDate: '24.00.00',
    hasKey: true,
    createDate: '24.00.00',
    securityDepositReturnStatus: 'PAYMENT',
  },
  {
    exitRequestmentId: 1,
    residentName: '김김김김',
    studentNumber: '99999999',
    dormitoryName: '명덕관(4인실)',
    roomSize: 0,
    roomNumber: 999,
    exitDate: '24.00.00',
    hasKey: true,
    createDate: '24.00.00',
    securityDepositReturnStatus: 'PAYMENT',
  },
  {
    exitRequestmentId: 1,
    residentName: '김김김김',
    studentNumber: '99999999',
    dormitoryName: '명덕관(4인실)',
    roomSize: 0,
    roomNumber: 999,
    exitDate: '24.00.00',
    hasKey: true,
    createDate: '24.00.00',
    securityDepositReturnStatus: 'PAYMENT',
  },
  {
    exitRequestmentId: 1,
    residentName: '김김김김',
    studentNumber: '99999999',
    dormitoryName: '명덕관(4인실)',
    roomSize: 0,
    roomNumber: 999,
    exitDate: '24.00.00',
    hasKey: true,
    createDate: '24.00.00',
    securityDepositReturnStatus: 'PAYMENT',
  },
  {
    exitRequestmentId: 1,
    residentName: '김김김김',
    studentNumber: '99999999',
    dormitoryName: '명덕관(4인실)',
    roomSize: 0,
    roomNumber: 999,
    exitDate: '24.00.00',
    hasKey: true,
    createDate: '24.00.00',
    securityDepositReturnStatus: 'PAYMENT',
  },
  {
    exitRequestmentId: 1,
    residentName: '김김김김',
    studentNumber: '99999999',
    dormitoryName: '명덕관(4인실)',
    roomSize: 0,
    roomNumber: 999,
    exitDate: '24.00.00',
    hasKey: true,
    createDate: '24.00.00',
    securityDepositReturnStatus: 'PAYMENT',
  },
  {
    exitRequestmentId: 1,
    residentName: '김김김김',
    studentNumber: '99999999',
    dormitoryName: '명덕관(4인실)',
    roomSize: 0,
    roomNumber: 999,
    exitDate: '24.00.00',
    hasKey: true,
    createDate: '24.00.00',
    securityDepositReturnStatus: 'PAYMENT',
  },
  {
    exitRequestmentId: 1,
    residentName: '김김김김',
    studentNumber: '99999999',
    dormitoryName: '명덕관(4인실)',
    roomSize: 0,
    roomNumber: 999,
    exitDate: '24.00.00',
    hasKey: true,
    createDate: '24.00.00',
    securityDepositReturnStatus: 'PAYMENT',
  },
  {
    exitRequestmentId: 1,
    residentName: '김김김김',
    studentNumber: '99999999',
    dormitoryName: '명덕관(4인실)',
    roomSize: 0,
    roomNumber: 999,
    exitDate: '24.00.00',
    hasKey: true,
    createDate: '24.00.00',
    securityDepositReturnStatus: 'PAYMENT',
  },
  {
    exitRequestmentId: 1,
    residentName: '김김김김',
    studentNumber: '99999999',
    dormitoryName: '명덕관(4인실)',
    roomSize: 0,
    roomNumber: 999,
    exitDate: '24.00.00',
    hasKey: true,
    createDate: '24.00.00',
    securityDepositReturnStatus: 'PAYMENT',
  },
];

export const Primary: Story = {
  args: {
    clickSchoolNumber: '99999998',
    list: list,
  },
};

export const Scroll: Story = {
  args: {
    clickSchoolNumber: '99999998',
    list: listScroll,
  },
};

export const NoneList: Story = {
  args: {
    list: [],
  },
};
