import type { Meta, StoryObj } from '@storybook/react';

import BlackList from './BlackList';

const meta: Meta<typeof BlackList> = {
  title: 'components/organisms/BlackList',
  component: BlackList,
  tags: ['autodocs'],
  argTypes: {},
};

export default meta;

type Story = StoryObj<typeof BlackList>;

export const primary: Story = {
  args: {
    blackLists: [
      {
        index: '001',
        name: '이보현',
        studentId: '60190814',
        phoneNumber: '010-1234-1234',
        minus: '342',
        reason: '말안들음',
        setReason: () => {},
        registrationDate: '23.12.12',
        isChecked: true,
        setIsChecked: () => {},
        isEdit: false,
      },
      {
        index: '001',
        name: '이보현',
        studentId: '60190814',
        phoneNumber: '010-1234-1234',
        minus: '342',
        reason: '말안들음',
        setReason: () => {},
        registrationDate: '23.12.12',
        isChecked: true,
        setIsChecked: () => {},
        isEdit: false,
      },
    ],
  },
};

export const scroll: Story = {
  args: {
    blackLists: [
      {
        index: '001',
        name: '이보현',
        studentId: '60190814',
        phoneNumber: '010-1234-1234',
        minus: '342',
        reason: '말안들음',
        setReason: () => {},
        registrationDate: '23.12.12',
        isChecked: true,
        setIsChecked: () => {},
        isEdit: false,
      },
      {
        index: '001',
        name: '이보현',
        studentId: '60190814',
        phoneNumber: '010-1234-1234',
        minus: '342',
        reason: '말안들음',
        setReason: () => {},
        registrationDate: '23.12.12',
        isChecked: true,
        setIsChecked: () => {},
        isEdit: false,
      },
      {
        index: '001',
        name: '이보현',
        studentId: '60190814',
        phoneNumber: '010-1234-1234',
        minus: '342',
        reason: '말안들음',
        setReason: () => {},
        registrationDate: '23.12.12',
        isChecked: true,
        setIsChecked: () => {},
        isEdit: false,
      },
      {
        index: '001',
        name: '이보현',
        studentId: '60190814',
        phoneNumber: '010-1234-1234',
        minus: '342',
        reason: '말안들음',
        setReason: () => {},
        registrationDate: '23.12.12',
        isChecked: true,
        setIsChecked: () => {},
        isEdit: false,
      },
      {
        index: '001',
        name: '이보현',
        studentId: '60190814',
        phoneNumber: '010-1234-1234',
        minus: '342',
        reason: '',
        setReason: () => {},
        registrationDate: '23.12.12',
        isChecked: true,
        setIsChecked: () => {},
        isEdit: true,
      },
      {
        index: '001',
        name: '이보현',
        studentId: '60190814',
        phoneNumber: '010-1234-1234',
        minus: '342',
        reason: '',
        setReason: () => {},
        registrationDate: '23.12.12',
        isChecked: true,
        setIsChecked: () => {},
        isEdit: true,
      },
      {
        index: '001',
        name: '이보현',
        studentId: '60190814',
        phoneNumber: '010-1234-1234',
        minus: '342',
        reason: '',
        setReason: () => {},
        registrationDate: '23.12.12',
        isChecked: true,
        setIsChecked: () => {},
        isEdit: true,
      },
      {
        index: '001',
        name: '이보현',
        studentId: '60190814',
        phoneNumber: '010-1234-1234',
        minus: '342',
        reason: '',
        setReason: () => {},
        registrationDate: '23.12.12',
        isChecked: true,
        setIsChecked: () => {},
        isEdit: true,
      },
      {
        index: '001',
        name: '이보현',
        studentId: '60190814',
        phoneNumber: '010-1234-1234',
        minus: '342',
        reason: '',
        setReason: () => {},
        registrationDate: '23.12.12',
        isChecked: true,
        setIsChecked: () => {},
        isEdit: true,
      },
      {
        index: '001',
        name: '이보현',
        studentId: '60190814',
        phoneNumber: '010-1234-1234',
        minus: '342',
        reason: '',
        setReason: () => {},
        registrationDate: '23.12.12',
        isChecked: true,
        setIsChecked: () => {},
        isEdit: true,
      },
      {
        index: '001',
        name: '이보현',
        studentId: '60190814',
        phoneNumber: '010-1234-1234',
        minus: '342',
        reason: '',
        setReason: () => {},
        registrationDate: '23.12.12',
        isChecked: true,
        setIsChecked: () => {},
        isEdit: true,
      },
      {
        index: '001',
        name: '이보현',
        studentId: '60190814',
        phoneNumber: '010-1234-1234',
        minus: '342',
        reason: '',
        setReason: () => {},
        registrationDate: '23.12.12',
        isChecked: true,
        setIsChecked: () => {},
        isEdit: true,
      },
      {
        index: '001',
        name: '이보현',
        studentId: '60190814',
        phoneNumber: '010-1234-1234',
        minus: '342',
        reason: '',
        setReason: () => {},
        registrationDate: '23.12.12',
        isChecked: true,
        setIsChecked: () => {},
        isEdit: true,
      },
      {
        index: '001',
        name: '이보현',
        studentId: '60190814',
        phoneNumber: '010-1234-1234',
        minus: '342',
        reason: '',
        setReason: () => {},
        registrationDate: '23.12.12',
        isChecked: true,
        setIsChecked: () => {},
        isEdit: true,
      },
      {
        index: '001',
        name: '이보현',
        studentId: '60190814',
        phoneNumber: '010-1234-1234',
        minus: '342',
        reason: '',
        setReason: () => {},
        registrationDate: '23.12.12',
        isChecked: true,
        setIsChecked: () => {},
        isEdit: true,
      },
      {
        index: '001',
        name: '이보현',
        studentId: '60190814',
        phoneNumber: '010-1234-1234',
        minus: '342',
        reason: '',
        setReason: () => {},
        registrationDate: '23.12.12',
        isChecked: true,
        setIsChecked: () => {},
        isEdit: true,
      },
      {
        index: '001',
        name: '이보현',
        studentId: '60190814',
        phoneNumber: '010-1234-1234',
        minus: '342',
        reason: '',
        setReason: () => {},
        registrationDate: '23.12.12',
        isChecked: true,
        setIsChecked: () => {},
        isEdit: true,
      },
      {
        index: '001',
        name: '이보현',
        studentId: '60190814',
        phoneNumber: '010-1234-1234',
        minus: '342',
        reason: '',
        setReason: () => {},
        registrationDate: '23.12.12',
        isChecked: true,
        setIsChecked: () => {},
        isEdit: true,
      },
      {
        index: '001',
        name: '이보현',
        studentId: '60190814',
        phoneNumber: '010-1234-1234',
        minus: '342',
        reason: '',
        setReason: () => {},
        registrationDate: '23.12.12',
        isChecked: true,
        setIsChecked: () => {},
        isEdit: true,
      },
      {
        index: '001',
        name: '이보현',
        studentId: '60190814',
        phoneNumber: '010-1234-1234',
        minus: '342',
        reason: '',
        setReason: () => {},
        registrationDate: '23.12.12',
        isChecked: true,
        setIsChecked: () => {},
        isEdit: true,
      },
      {
        index: '001',
        name: '이보현',
        studentId: '60190814',
        phoneNumber: '010-1234-1234',
        minus: '342',
        reason: '',
        setReason: () => {},
        registrationDate: '23.12.12',
        isChecked: true,
        setIsChecked: () => {},
        isEdit: true,
      },
      {
        index: '001',
        name: '이보현',
        studentId: '60190814',
        phoneNumber: '010-1234-1234',
        minus: '342',
        reason: '',
        setReason: () => {},
        registrationDate: '23.12.12',
        isChecked: true,
        setIsChecked: () => {},
        isEdit: true,
      },
      {
        index: '001',
        name: '이보현',
        studentId: '60190814',
        phoneNumber: '010-1234-1234',
        minus: '342',
        reason: '',
        setReason: () => {},
        registrationDate: '23.12.12',
        isChecked: true,
        setIsChecked: () => {},
        isEdit: true,
      },
      {
        index: '001',
        name: '이보현',
        studentId: '60190814',
        phoneNumber: '010-1234-1234',
        minus: '342',
        reason: '',
        setReason: () => {},
        registrationDate: '23.12.12',
        isChecked: true,
        setIsChecked: () => {},
        isEdit: true,
      },
      {
        index: '001',
        name: '이보현',
        studentId: '60190814',
        phoneNumber: '010-1234-1234',
        minus: '342',
        reason: '',
        setReason: () => {},
        registrationDate: '23.12.12',
        isChecked: true,
        setIsChecked: () => {},
        isEdit: true,
      },
      {
        index: '001',
        name: '이보현',
        studentId: '60190814',
        phoneNumber: '010-1234-1234',
        minus: '342',
        reason: '',
        setReason: () => {},
        registrationDate: '23.12.12',
        isChecked: true,
        setIsChecked: () => {},
        isEdit: true,
      },
      {
        index: '001',
        name: '이보현',
        studentId: '60190814',
        phoneNumber: '010-1234-1234',
        minus: '342',
        reason: '',
        setReason: () => {},
        registrationDate: '23.12.12',
        isChecked: true,
        setIsChecked: () => {},
        isEdit: true,
      },
    ],
  },
};

export const noData: Story = {
  args: {
    blackLists: [],
  },
};
