import type { Meta, StoryObj } from '@storybook/react';

import page from './page';

const meta: Meta<typeof page> = {
  title: 'app/FAQ/FAQ',
  component: page,
  tags: ['autodocs'],
  argTypes: {},
};

export default meta;

type Story = StoryObj<typeof page>;

export const Primary: Story = {
  args: {
    pageNum: 1,
    pageTotalNum: 3,
    faqLists: [
      {
        index: '1',
        title: '2024-1 전자식권 사용방법 안내(식당/편의점/카페)',
        writer: '이보현',
        registrationDate: '2020.20.20',
        isExistedFile: true,
        views: 999,
        isPinned: true,
      },
      {
        index: '1',
        title: '2024-1 전자식권 사용방법 안내(식당/편의점/카페)',
        writer: '이보현',
        registrationDate: '2020.20.20',
        isExistedFile: true,
        views: 999,
        isPinned: false,
      },
      {
        index: '1',
        title: '2024-1 전자식권 사용방법 안내(식당/편의점/카페)',
        writer: '이보현',
        registrationDate: '2020.20.20',
        isExistedFile: true,
        views: 999,
        isPinned: true,
      },
      {
        index: '1',
        title: '2024-1 전자식권 사용방법 안내(식당/편의점/카페)',
        writer: '이보현',
        registrationDate: '2020.20.20',
        isExistedFile: true,
        views: 999,
        isPinned: false,
      },
      {
        index: '1',
        title: '2024-1 전자식권 사용방법 안내(식당/편의점/카페)',
        writer: '이보현',
        registrationDate: '2020.20.20',
        isExistedFile: true,
        views: 999,
        isPinned: true,
      },
      {
        index: '1',
        title: '2024-1 전자식권 사용방법 안내(식당/편의점/카페)',
        writer: '이보현',
        registrationDate: '2020.20.20',
        isExistedFile: true,
        views: 999,
        isPinned: false,
      },
      {
        index: '1',
        title: '2024-1 전자식권 사용방법 안내(식당/편의점/카페)',
        writer: '이보현',
        registrationDate: '2020.20.20',
        isExistedFile: true,
        views: 999,
        isPinned: true,
      },
      {
        index: '1',
        title: '2024-1 전자식권 사용방법 안내(식당/편의점/카페)',
        writer: '이보현',
        registrationDate: '2020.20.20',
        isExistedFile: true,
        views: 999,
        isPinned: false,
      },
      {
        index: '1',
        title: '2024-1 전자식권 사용방법 안내(식당/편의점/카페)',
        writer: '이보현',
        registrationDate: '2020.20.20',
        isExistedFile: true,
        views: 999,
        isPinned: true,
      },
      {
        index: '1',
        title: '2024-1 전자식권 사용방법 안내(식당/편의점/카페)',
        writer: '이보현',
        registrationDate: '2020.20.20',
        isExistedFile: true,
        views: 999,
        isPinned: false,
      },
      {
        index: '1',
        title: '2024-1 전자식권 사용방법 안내(식당/편의점/카페)',
        writer: '이보현',
        registrationDate: '2020.20.20',
        isExistedFile: true,
        views: 999,
        isPinned: true,
      },
      {
        index: '1',
        title: '2024-1 전자식권 사용방법 안내(식당/편의점/카페)',
        writer: '이보현',
        registrationDate: '2020.20.20',
        isExistedFile: true,
        views: 999,
        isPinned: false,
      },
      {
        index: '1',
        title: '2024-1 전자식권 사용방법 안내(식당/편의점/카페)',
        writer: '이보현',
        registrationDate: '2020.20.20',
        isExistedFile: true,
        views: 999,
        isPinned: true,
      },
      {
        index: '1',
        title: '2024-1 전자식권 사용방법 안내(식당/편의점/카페)',
        writer: '이보현',
        registrationDate: '2020.20.20',
        isExistedFile: true,
        views: 999,
        isPinned: false,
      },
      {
        index: '1',
        title: '2024-1 전자식권 사용방법 안내(식당/편의점/카페)',
        writer: '이보현',
        registrationDate: '2020.20.20',
        isExistedFile: true,
        views: 999,
        isPinned: true,
      },
      {
        index: '1',
        title: '2024-1 전자식권 사용방법 안내(식당/편의점/카페)',
        writer: '이보현',
        registrationDate: '2020.20.20',
        isExistedFile: true,
        views: 999,
        isPinned: false,
      },
      {
        index: '1',
        title: '2024-1 전자식권 사용방법 안내(식당/편의점/카페)',
        writer: '이보현',
        registrationDate: '2020.20.20',
        isExistedFile: true,
        views: 999,
        isPinned: true,
      },
      {
        index: '1',
        title: '2024-1 전자식권 사용방법 안내(식당/편의점/카페)',
        writer: '이보현',
        registrationDate: '2020.20.20',
        isExistedFile: true,
        views: 999,
        isPinned: false,
      },
      {
        index: '1',
        title: '2024-1 전자식권 사용방법 안내(식당/편의점/카페)',
        writer: '이보현',
        registrationDate: '2020.20.20',
        isExistedFile: true,
        views: 999,
        isPinned: true,
      },
      {
        index: '1',
        title: '2024-1 전자식권 사용방법 안내(식당/편의점/카페)',
        writer: '이보현',
        registrationDate: '2020.20.20',
        isExistedFile: true,
        views: 999,
        isPinned: false,
      },
      {
        index: '1',
        title: '2024-1 전자식권 사용방법 안내(식당/편의점/카페)',
        writer: '이보현',
        registrationDate: '2020.20.20',
        isExistedFile: true,
        views: 999,
        isPinned: true,
      },
      {
        index: '1',
        title: '2024-1 전자식권 사용방법 안내(식당/편의점/카페)',
        writer: '이보현',
        registrationDate: '2020.20.20',
        isExistedFile: true,
        views: 999,
        isPinned: false,
      },
    ],
  },
};
